ColdBox/coldbox-platform

- system/core/dynamic/HTMLHelper.cfc
addAsset should now recognize urls that ends with say "app.js?123" as js, not css.
> Fixed addAsset to better handle "tagged" js urls

- box-wirebox-cachebox.json
- box-wirebox.json
Just a super simple housekeeping PR to satisfy the requirements of https://ortussolutions.atlassian.net/browse/WIREBOX-45.
The document links are now up to date.
> WIREBOX-45 Update the documentation URL in box.json

- system/core/dynamic/HTMLHelper.cfc
German umlauts should be replace like this:
ä to ae
ü to ue
ö to oe
ß to ss
> slugify doesn't make nice German slugs

- system/interceptors/SES.cfc
- system/testing/BaseTestCase.cfc
- system/web/context/RequestContext.cfc
- test-harness/config/routes.cfm
Allow a url to be passed to the `execute()` function.  The `BaseTestCase` will then parse the url and set up the SES interceptor.  This allows testing of routes as well as events.
> Add url option to execute for coldbox integration testing

- system/aop/Mixer.cfc
`getFileInfo()` requires "Absolute on-disk or in-memory path". fixed for CF9+
> getFileInfo() requires "Absolute on-disk or in-memory path"

- system/core/dynamic/HTMLHelper.cfc
- system/web/Renderer.cfc
- system/web/config/ApplicationLoader.cfc
- system/web/config/Settings.cfc
- system/web/services/ModuleService.cfc
New elixir function that returns the versioned path for a file.
This allows us to cache bust and version using ColdBox Elixir.
```cfm
<script src="#elixir( 'js/all.js' )#"></script>
// =>
<script src="/includes/build/js/all-dd0e0acd94.js"></script>
```
If we can't find the versioned path, we return the normal convention path.
```cfm
<script src="#elixir( 'css/all.css' )#"></script>
// =>
<script src="/includes/css/all.css"></script>
```
The `appMapping` is also taken into account if there is one:
```cfm
// appMapping = "/testapp"
<script src="#elixir( 'js/all.js' )#"></script>
// =>
<script src="/testapp/includes/build/js/all-dd0e0acd94.js"></script>
```
---
This pull request also introduces a new configurable `includesLocation` option.
`includesConvention` can be overwritten in the …
> Elixir function for versioned assets

- system/logging/LogBox.cfc
Allows easier programmatic configuration of LogBox (i.e. for use with modules).
> Make getAppendersMap public

- system/web/context/RequestContext.cfc
In some situations the response from the `getHTMLBaseURL` is returns with a double slash at the end, e.g.:
`http://www.mydomain.com//`
instead of:
`http://www.mydomain.com/`
This change fixes that by changing the replace to a regex replace and adding an optional slash after `index.cfm`.
> Fixing response URL

- system/testing/BaseTestCase.cfc
This lets you test like so:
```cfc
var event = execute( route = "/", renderResults = true );
```
Which, by default, would execute `Main.index`.
> Use the default event if the route passed in is the base route (`/`)

- system/logging/Logger.cfc
Allow string literals ("WARN", "DEBUG", etc.) to be passed in to `setLevelMin` and `setLevelMax`.
> Allow string levels in setLevel methods

- system/testing/BaseTestCase.cfc
This causes issues with the app thinking there was no route passed in when there really was.
> Don't keep branching if the root page ("/") was found

- system/web/services/ModuleService.cfc
By convention, look for a struct in the `config/ColdBox.cfc` parent configuration's `moduleSettings` struct matching the module's namespace.
If it is found and the `this.parseParentSettings` flag is `true` (default), then merge the parent config struct in to the module settings struct.
Then set the new module settings struct as the settings in the parent configuration.
Otherwise, the module settings override any settings in the `config/ColdBox.cfc`
Examples:
```cfc
// ModuleConfig.cfc
component {
this.modelNamespace = "cbsvg"; // defaults to module name
this.parseParentSettings = true; // default value
function configure() {
settings = {
inline = false
class = "icon"
};
}
}
// config/ColdBox.cfc
component {
function configure() {
moduleSettings = {
cbsvg = {
inline = true
}
};
}
}
// …
```
> Parse parent settings by convention for modules

- system/ioc/Injector.cfc
- system/ioc/config/Binder.cfc
- tests/specs/ioc/config/BinderTest.cfc
This enables modules to add new listeners (like the AOP listener) and have them activated.
> Allow new listeners added to the Binder to also be registered right away

- system/web/services/ModuleService.cfc
- test-harness/config/Coldbox.cfc
- tests/specs/integration/ModuleTests.cfc
This bug was introduced when adding the parse parent settings by convention for modules (https://github.com/ColdBox/coldbox-platform/pull/289).
Instead of updating the module namespace in the `moduleSettings` struct to match, it updated the module namespace in the `settings` struct.
Some modules depended on the old behavior, especially those that rolled their own parse parent settings.
This pull request fixes the behavior so that the module's settings and the module namespace in `moduleSettings` are kept in sync.  `settings` is not touched.
> Fix bug where modules would override the settings struct of config/ColdBox.cfc

- system/interceptors/SES.cfc
- system/web/context/RequestContext.cfc
- test-harness/handlers/rendering.cfc
- test-harness/models/ControllerDecorator.cfc
- tests/specs/integration/RestfulTests.cfc
- tests/specs/interceptors/SESTest.cfc
This pull request has two main parts:
1. If format isn't set in the `rc` scope and isn't detected via an extension `users.json`, the SES interceptor will attempt to use the `Accept` header to figure out what format to use.
2. If using `renderData` with multiple `formats` and new parameter of `formatsRedirectEvent` is allowed to redirect ONLY for HTML formats.  The struct is passed as the `argumentCollection` for `setNextEvent`.
See https://ortussolutions.atlassian.net/browse/COLDBOX-36
> Format detection from accepts header & redirect event on HTML events with multiple formats

- system/web/services/ModuleService.cfc
Perfect example of why it is necessary to test with cfengine=adobe@11 - this causes cbox-debugger to fail to load the app entirely.
> Invalid construct.A script statement must end with ";"

- system/core/util/Util.cfc
- system/web/config/ApplicationLoader.cfc
- system/web/services/ModuleService.cfc
This pull request is the spiritual successor to https://github.com/ColdBox/coldbox-platform/pull/291
cc @lmajano @bdw429s @jclausen 
Usage:
+ `getSystemSetting( key, defaultValue )` -> looks in properties first, env second. Returns the `defaultValue` if neither exist. 
+ `getSystemProperty( key, defaultValue )` -> Returns the Java System property.  Returns the `defaultValue` if does not exist.
+ `getEnv( key, defaultValue )` -> Returns the Env property.  Returns the `defaultValue` if does not exist.
These helper methods are available in the `config/ColdBox.cfc` file and all `ModuleConfig.cfc` files.
> Provide helper methods for system settings that covers both properties (first) and env variables.

- system/interceptors/SES.cfc
- tests/specs/interceptors/SESAddResourceTest.cfc
Let me know if we're good on this and I'll get a pull request going for the docs as well. Thanks to @elpete for a lot of help on this one.
`addResource` is a method for quickly scaffolding the RESTful routes for a resource
Calling `addResource( "photos" )` would create the following routes: ([taken from the Rails Routing Guide](http://edgeguides.rubyonrails.org/routing.html))
HTTP Verb | Path | Handler.Action | Used For
----------- | -----| ---------------|----------------
GET | /photos | photos.index | Display a list of photos.
GET | /photos/new | photos.new | Return an HTML form for creating a new photo.
POST | /photos | photos.create | Create a new photo.
GET | /photos/:id | photos.show | Display a specific photo.
GET | /photos/:id/edit | photos.edit | Return an HTML form for editing a …
> Adding an addResource method which creates the RESTful routes for a resource

- system/ioc/dsl/ColdBoxDSL.cfc
- tests/specs/ioc/dsl/ColdBoxDSLTest.cfc
To get the request-scoped instance, simply use the provider: `coldbox:requestContext`.
If you are using this in anything other than request-scoped or other transient-scoped, use a provider: `provider:coldbox:requestContext`.  A reminder that methods will be forwarded on to the provided instance.  That means:
```cfc
component {
property name="event" inject="provider:coldbox:requestContext";
function doStuff() {
var rc = event.getCollection();
// same as
var rc = event.get().getCollection();
}
}
```
works just fine, with or without calling `get` first.
> Add new request context dsl injection.

- system/web/context/RequestContext.cfc
- tests/specs/web/context/requestcontextTest.cfc
The `only` method lets you whitelist the keys you want returned from the request context.
Usage:
```
rc = { "email" = "john@example.com", "password" = "pass1234" };
var fields = event.only( [ "email", "username" ] );
// fields = { "email" = "john@example.com" };
```
> Add only method to filter to only desired keys

- system/testing/BaseTestCase.cfc
In order to prevent things like duplicate headers, reset the response when calling setup in between tests.
> Reset the response when calling setup

- system/web/services/ModuleService.cfc
- test-harness/modules/Inception/modules/a-inception/ModuleConfig.cfc
- test-harness/modules/Inception/modules/a-inception/handlers/Home.cfc
- test-harness/modules/Inception/modules/a-inception/views/home/index.cfm
- tests/specs/integration/ModuleTests.cfc
Fixes [COLDBOX-604](https://ortussolutions.atlassian.net/browse/COLDBOX-604)
> Ensure modules are only activated once, even if it is a child module of one of its dependencies.

- system/remote/ColdboxProxy.cfc
This appears to have been a regression when converting Controller.cfc to cfscript format in this commit: e969c3742ca34b6ad8a05bfc946caec85a01fbc7
> Fixed: overrideEvent() not working from proxy context

- system/ioc/dsl/ColdBoxDSL.cfc
if setting struct is incomplete, error message is hard to understand. Improve check for key
> Updated check for setting key

- system/testing/BaseTestCase.cfc
- system/testing/mock/web/context/MockRequestContext.cfc
- system/web/services/RequestService.cfc
This allows easy access to the status code set during the event execution
as well as other render data properties.
> Add helpers for render data and status code to integration testing

- system/testing/BaseTestCase.cfc
- system/web/Controller.cfc
- system/web/services/HandlerService.cfc
- test-harness/handlers/main.cfc
- tests/specs/integration/EventExecutions.cfc
Right now, both of these have a default status code of 200.  This is especially troublesome with ajax requests since a 200 _thinks_ it passed even though it failed.  You could always set an `invalidEvent` or `onException` handler, but this sets those status codes by default.
As a side benefit, the integration testing `getStatusCode` helper now works in more situations (like view rendering) and there is a new `withExceptionHandling` to use exception handling (like the global `onException` handler) with integration tests.
> Set default status code for invalid event and exceptions

- system/testing/BaseTestCase.cfc
Having an annotation of `@beforeAll` on `beforeAll` and `@afterAll` on `afterAll` cause them to be executed twice.
> Remove annotations on beforeAll and afterAll

- system/testing/BaseTestCase.cfc
Adds a `request` method along with `get`, `post`, `put`, `patch`, and `delete` methods.
These methods take a route, a struct of params, and a struct of headers and set up the `execute` method as needed.
Here's a compare and contrast.
Current way using `execute` directly:
```cfc
prepareMock( getRequestContext() )
.$( "getHTTPMethod", "POST" )
.setValue( "email", "john@example.com" )
.setValue( "password", "pass1234" );
var event = execute( route = "/login" );
```
New way using `post`:
```cfc
var event = post( "/login", {
"email" = "john@example.com",
"password" = "pass1234"
} );
```
> Add Test Request Helpers

- system/web/context/RequestContext.cfc
This gets the url as it was executed from the callee.
This is needed for some signature verifications.
> Add getFullURL method

- system/ioc/Builder.cfc
- system/web/services/ModuleService.cfc
- tests/specs/integration/ModuleTests.cfc
This PR adds the ability to use an `id` injection with a module.
Just as the `id` DSL uses the name of the model as the mapping,
this adds a similar DSL for modules using `@#moduleNamespace#`.
```
property name="MyService" inject="id";
// should inject the dependency mapped to `MyService`
property name="MyService" inject="@myModule";
// should inject the dependency mapped to `MyService@myModule`
```
This also removes the old (beta) behavior of registering a default export in the ModuleService.
The good news is this will still work as long as the name being injected is the name of the module.
```
property name="bcrypt" inject="@Bcrypt";
// This works because the model name in Bcrypt is `Bcrypt`
property name="encrypt" inject="@Bcrypt";
// This will not work anymore because `encrypt@Bcrypt` …
```
> Add a module id injection DSL.

- system/ioc/config/Binder.cfc
Excluding the path gives the new mapping no where to point to.
> Don't exclude path in parent mapping destinations

- system/modules/HTMLHelper/models/HTMLHelper.cfc
Prevent wrong filetype attribution when an url contains ".js"
> Fix ColdBox-597

- system/modules/HTMLHelper/models/HTMLHelper.cfc
Without this, if you set a column, but not columnName, it will not use the default 'name' field, it will overwrite it with the column field ( value ) because of the else.
Tested locally, this works.
Update of pull request after new file location and conversion of tag to script.
https://github.com/ColdBox/coldbox-platform/pull/357
> Fix a requirement for columnName if column is defined - new

- system/testing/BaseTestCase.cfc
https://ortussolutions.atlassian.net/browse/COLDBOX-736
When you don't unload the coldbox framework inside your integration tests, coldbox lives in memory across page requests to your tests. This means your CF mappings disappear and the base test case does nothing to ensure the CF mappings for the modules still exist. We need to ensure module mappings are present when loadcoldbox is true.
> COLDBOX-736

- system/web/routing/Router.cfc
Module- and Namespace-Routes couldn't be prepended because of a typo in the function calls for prePend().
> Fixed typo(s) in call of function prePend()

- system/logging/config/LogBoxConfig.cfc
- tests/specs/logging/LogBoxTest.cfc
Adding a category after LogBox had already been configured errored because the `*` appenders wasn't expanded.  This PR expands the appenders in the `category` method, if needed.
> Add test and fix for adding a LogBox category after the fact

- system/testing/BaseTestCase.cfc
- system/web/services/HandlerService.cfc
- tests/specs/integration/MainImplicitTest.cfc
https://ortussolutions.atlassian.net/browse/COLDBOX-761
It does this by caching the last tried event in the `request` scope so it can see if it is not changing at all.
> Catch stack overflows when the invalidEventHandler isn't an event at all

- system/ioc/Builder.cfc
This addresses an issue with an unscoped argument reference. See: https://ortussolutions.atlassian.net/browse/COLDBOX-763 for detail.
Wasn't sure what preference you had re naming copy of arguments scope here for reference in closures, but have gone with `args` for now.
Had a quick look to see where I could add tests but train pulling into station and running out of time, so no time to provide a test case for this particular scenario, apologies.
> COLDBOX-763 scope target var

- system/web/Controller.cfc
When the prePostExempt flag is up, the `aroundHandler` method should also be excluded from firing, otherwise the eventArguments passed to the `runEvent` method can be completely overridden or reconstructed.
> Excludes aroundHandler from firing when prePostExempt

- home/dom/code/coldbox-platform/tests/logs/commandbox.log
- system/aop/Mixer.cfc
- system/cache/store/ConcurrentSoftReferenceStore.cfc
- system/cache/store/ConcurrentStore.cfc
- system/cache/store/indexers/MetadataIndexer.cfc
- system/ioc/scopes/Singleton.cfc
The following changes are focused on Cachebox but also touch on a couple of other uses of `java.util.concurrent.ConcurrentHashMap` in Coldbox.
The crux is that, in Lucee at least, using CFML Struct functions on instances of `java.util.concurrent.ConcurrentHashMap` are *not thread safe*, negating the purpose of using it. For instance, our application error logs show sporadic instances of `ArrayIndexOutOfBounds` and other `variable does not exist` errors in Cachebox:
```cfc
component {
// ...
instance.pool = createObject( "java", "java.util.concurrent.ConcurrentHashMap" ).init();
// ...
function getKeys() {
return StructKeyArray( instance.pool ); // <<< throws ArrayIndexOutOfBounds error while pool is having keys cleared
}
}
```
This change, then, makes use of the java methods directly …
> CACHEBOX-46 Cachebox concurrency

- system/web/context/RequestContext.cfc
Currently `getHTMLBaseURL()` returns the port number if it is displayed in the address bar. It seems like `getFullURL()` should also include the port number if displayed as well.  Having the port displayed is especially important if you have a `<base>` tag in your layout and use anchor links (e.g. `<a href="#event.getFullURL()###anchor"...`.  
current:
`event.getHTMLBaseURL()` = `http://127.0.0.1:52606/`
`event.getFullURL()` = `http://127.0.0.1/handler/action/`
proposed:
`event.getHTMLBaseURL()` = `http://127.0.0.1:52606/`
`event.getFullURL()` = `http://127.0.0.1:52606/handler/action/`
> Update RequestContext.cfc getFullUrl() to include port number

- system/includes/BugReport.cfm
Adobe coldfusion returns false when executing isStruct() against an exception struct. This caused the default coldbox error template to not show the SQL exception details.
Added in another statement to check the underlying class name of the exception struct to determine if it is a database exception.
> Fix default bug report to show SQL error detail for adobe SQL exceptions

- system/web/routing/Router.cfc
- tests/specs/web/routing/ResourcesTest.cfc
- tests/specs/web/routing/RouterTest.cfc
Currently, the following doesn't work as expected:
```
router.post( "photos/", "photos.create" );
router.get( "photos/", "photos.index" );
```
You would expect then you could either `GET` or `POST` to `photos/`.  This is not the case.  Instead this creates two routes.  If you tried to `GET /photos` you would match the route that only has a `POST` verb and it would give you an error of an invalid HTTP verb.
This PR attempts to merge routes when a route with a matching pattern already exists in the routing table.
> Initial pass at merging HTTP verbs for the same route

- .cfconfig.json
- system/logging/Logger.cfc
- system/logging/appenders/FileAppender.cfc
- system/web/Controller.cfc
- system/web/Renderer.cfc
- system/web/RendererEncapslator.cfm
- system/web/context/InterceptorState.cfc
- tests/specs/web/context/interceptorStateTest.cfc
This allows the renderer to be a singleton with NO thread safety issues.  CFModule is used to render views which fully encapsulates their variables scope inside the module call.  Request-specific instance data has been moved from the renderer.  In an example page that calls renderView() 3,000 times, the overall page time dropped from 9 seconds to 700 ms with my changes.   The full test suite is passing on Lucee and Adobe.  This pull also contains fixes necessary for the test suite to even work on Adobe without crashing, including changes to cfthread to avoid messy and costly duplication of CFC instances.
> Singleton renderer

- system/web/services/RequestService.cfc
- system/web/services/RoutingService.cfc
- tests/specs/web/routing/RoutingServiceTest.cfc
Because the `RoutingService` registered itself as an interceptor, you couldn't guarantee that it would be ran before any other `onRequestCapture` points.  This change ensures that the request is processed and the `rc` and `prc` scopes filled before calling interceptors.
> Capture request before announcing onRequestCapture

- system/core/conversion/XMLConverter.cfc
- tests/specs/core/conversion/XMLConverterTest.cfc
The invoke incorrectly included "()" in with the method name which is not required
> Updated invoke() to correctly call method by name

- system/remote/ColdboxProxy.cfc
- test-harness/views/main/routeTable.cfm
When instantiating components on the application start, autowiring is failing due to the proxy component path being retrieved from the script name in the CGI scope, which was not taking into consideration a defined context root in the webserver.
> Self-autowire fails for applications with context root configured

- system/web/context/RequestContext.cfc
- tests/specs/web/context/RequestContextTest.cfc
This is used mainly to apply active classes to a link or section.
It matches partial paths by default.  An `exact` flag or the
`urlMatchesExact` method can be used to only do exact path matches.
> feat(RequestContext): Add urlMatches to match current urls

- system/web/routing/Router.cfc
Standardize to use `valuePairTranslation` instead of `valuePairTranslator`
> COLDBOX-839 - Resolve router method/arg discrepancy

- system/exceptions/Whoops.cfm
Previously if you clicked on the exception message, it would automatically highlight all of the text which makes it difficult to select just a subset. For example, if you just needed to copy a variable name which caused the exception and not the whole message.  This change does not break the "copy to clipboard" button which will still enable users to do so if they need the entire message on their clipboard.  This change gives the feature a little more flexibility with that box.
> Update "Whoops" exception message to allow selecting a subset of text

- system/cache/report/skins/default/CacheReport.cfm
DateFormat mask to use lowercase "d" due to ColdFusion 2021 breaking change.  ("D" now outputs "day of year".)
More info here:
https://www.carehart.org/blog/client/index.cfm/2020/11/24/breaking_change_in_cf2021_dateformat_D_vs_d
> Update DateFormat Mask to use lowercase "d".

- system/ioc/config/Binder.cfc
- system/ioc/config/Mapping.cfc
Fix initArg() and addDIConstructorArgument() calls
Problem is exposed when:
initArg(name="Something", ref="AnID")
Upon init, Wirebox sees a dsl="" and doesn't know what to do.
> Remove default dsl of "" from initArg() and addDIConstructorArgument()

- system/web/context/RequestContext.cfc
The current implementation would append an extra slash.  This caused a cascading failure when used with Inertia because Inertia used this value to set the URL.
> Use Java URI for more resiliasnt getFullURL

- system/ioc/config/Binder.cfc
`map( "Mapping", true )` is difficult to understand the intent of the `true` argument (`force`).
`forceMap( "Mapping" )` makes this boolean flag unnecessary and coveys the intent of the method.
> Add a forceMap method as a shortcut to map( alias, force )

- system/web/routing/Router.cfc
- tests/specs/web/routing/RouterTest.cfc
Conditions are a way to apply a function check before executing a route.  However, ColdBox also tries to intelligently merge routes when only the actions are different.  Conditions are tricky since they are functions and therefore not equatable or hashable. Because of this, if a condition is specified on a route always create a new route.  We will trust the developer not to make duplicate conditional routes.  And even if they do, ColdBox will handle it just fine.
> Always register new routes when conditions are provided

- system/web/services/HandlerService.cfc
Previously, if the handler existed but the action was incorrect, the invalid event lifecycle would not fire correctly.  To fix this, we override the event in the request context to be the invalid event handler event.
Fixes COLDBOX-964
> Ensures the invalid event handler is fired correctly

- system/web/routing/Router.cfc
- tests/specs/web/routing/RouterTest.cfc
The [ColdBox docs](https://coldbox.ortusbooks.com/the-basics/routing/routing-dsl/resourceful-routes) state that you can declare multiple resources at once in the `Router.cfc#resources` method, either as an array
or as a list.  In practice, neither work completely.  An array throws an error in the framework and a list does not use the correct handler.  This commit fixes that behavior, but with some caveats.
First, the handler is no longer defaulted in the parameter list. It is instead defaulted each loop through the resources.  If you are only passing in the first argument to `resources` nothing really changes.  If you specify the `handler` argument manually, it will use that handler for each loop.
This is fine for registering a single resource, but is probably not what you want for …
> Fix declaring multiple resources at once

- system/core/conversion/DataMarshaller.cfc
Remove boolean type check for jsonQueryFormat to allow passing 'row', 'column'  or 'struct' to serializeJson(). This was a regression from earlier releases.
[COLDBOX-981](https://ortussolutions.atlassian.net/browse/COLDBOX-981)
> Remove boolean type for jsonQueryFormat, allow ANY

- system/web/Controller.cfc
Simular functionality as in buildLink, makes it easier to add params
> querystring can also be a struct in relocate

- system/logging/Logger.cfc
async logger had no category, instead some default category or appendername was reported
see
https://ortussolutions.atlassian.net/browse/COLDBOX-1001
for details
> fix category for async logger

- system/core/dynamic/BeanPopulator.cfc
- system/core/util/Util.cfc
The `ormGetSessionFactory().getAllClassMetadata()` syntax is deprecated (and throws an error!) in Hibernate v5+, but ColdBox only switches syntax based on the Coldfusion server name. :/ 
This PR updates ColdBox to support the newest version of the Lucee Hibernate extension.
> Update BeanPopulator for Hibernate 5 in Lucee

- system/web/context/RequestContext.cfc
When Lucee's NULL support is enabled (see resolved COLDBOX-1010 which has `this.nullsupport=true` in the Application.cfc), I found a specific location that stops ColdBox from loading when running a rest-hmvc installation.
In the past structKeyExists returned false if the key did exist but was assigned a NULL.  With null support enabled, if the key was created and was given a value of NULL, the old comparison no longer works.  Because you're following that up with a javacast() call, we need to add an additional !isNull() check.
> COLDBOX-1010: Add isNull checks

- system/cache/report/skins/default/CacheContentReport.cfm
Replace IIF and urlEncodedFormat with modern versions
Use of `IIF` is discouraged as it evaluates the expression
Use of `urlEncodedFormat` is discouraged in deference to more specialised versions
This change will apply to Cachebox and therefore ColdBox and Wirebox
> Replace IIF and urlEncodedFormat

- system/web/routing/Router.cfc
- system/web/services/RoutingService.cfc
- tests/specs/web/routing/RouterTest.cfc
- tests/specs/web/routing/RoutingServiceTest.cfc
Multiple methods targeting the same route but with different HTTP verbs will now correctly configure the route to call the correct action.
Additionally, actions for a specific pattern can now point to different handlers, if desired.
Resolves COLDBOX-1027
> Better handling of different HTTP verb methods for the same route

- system/modules/HTMLHelper/models/HTMLHelper.cfc
The KEY being generated was based off the href, which included the app mapping, which is incorrect.
Since my manifest file is from the root of the app, the app mapping would never be in the key, and therefore this was not working.
By making these changes, it works as it was previously for apps in the root, but now has a chance to work in apps in subfolders.
If i ask for 
css/app.css in /gavin/publications 
it was looking for the key /gavin/publications/includes/css/app.css in the manifest - but it was /includes/css/app.css
So it usually just spits out what i put in there, 
So i was trying to hack it with /includes/css/app.css but it was just giving it back to me because /gavin/publications/includes/includes/css/app.css doesn't exist, so it works in dev, but it would never give me the …
> Fix Elixir Path for Apps in Subfolders

- .gitignore
- apidocs/Application.cfc
- apidocs/box.json
- system/async/proxies/BaseProxy.cfc
- system/testing/BaseTestCase.cfc
- tests/specs/async/AsyncManagerSpec.cfc
Ensure all coldbox.system.testing cfcs are able to reference testbox when building documentation. Resolves an issue where the `BaseInterceptorTest`, `BaseModelTest`, etc. files were excluded from the documentation output due to a missing `testbox` dependency.
> 📖 DOC: Add testbox to apidocs build for full coldbox documentation

- system/cache/store/JDBCStore.cfc
There is a limitation in ACF engines that requires all `queryExecute()` statements run within a `transaction` to have identical `datasource`, `username`, and `password` options.  This makes BDD integration testing extremely difficult if you utilize the JDBC store in Cachebox along with any other queries in a request.  Many modern CFML developers do not include the DSN, username, or password in each query and instead rely on setting it in the application.cfc.
This change dynamically builds the options struct which will be passed to queryExecute statements to give developers more flexibility in how the JDBC store will generate queryExecute statements so it can better match other queries in their code.   The addition of the new `queryIncludeDsn` will force the DSN to be included in all …
> Dynamically generate queryExecute options + new config to always include DSN

- system/async/proxies/BaseProxy.cfc
- system/testing/BaseTestCase.cfc
- system/web/routing/Router.cfc
- tests/specs/async/AsyncManagerSpec.cfc
- tests/specs/web/routing/RouterTest.cfc
The following now merges the routes correctly:
```cfc
router.post( "/notifications/read", "Notifications.ReadNotifications.create" );
router.route( "/notifications/read" )
.withHandler( "Notifications.ReadNotifications" )
.toAction( { "POST": "create", "DELETE": "delete" } );
```
It will also log a warning if any verbs are overwritten (since that is likely just a mistake).
> Fix instance of bad route merging

- system/core/util/Util.cfc
- system/ioc/Injector.cfc
- system/web/context/InterceptorState.cfc
- tests/specs/ioc/scopes/CFScopesTest.cfc
Adds `onException` interception support for allowing error handling on async interceptions. Previously, only the `processAsyncAll()` method supported this.
> Announce onException on async interceptor error

- system/cache/store/indexers/JDBCMetadataIndexer.cfc
A similar solution as https://ortussolutions.atlassian.net/browse/CACHEBOX-80.
This change dynamically generates the options for each queryExecute() statement based on the configuration data so it remains consistent with the JDBCStore.
> Dynamically generate QueryExecute options based on config data

- system/cache/store/indexers/JDBCMetadataIndexer.cfc
- system/ioc/config/Mapping.cfc
This cancels out CBORM-34 and the corresponding pull request by restoring the proper fall through behavior for attribute parsing
> Resolves WIREBOX-126 and cleans up legacy conditional operators

- system/RestHandler.cfc
This change allows for more customizable 404 entity not found exception responses. This should benefit everyone using Quick since methods like `findOrFail()` provide a default exception message and it can be customized via arguments.  Passing the message through to the client will help create more friendly (and detailed) error messages.  Users can also default to the generic message by providing an empty string as `exception.message` as well.
> Enhance EntityNotFound Exception Message

- system/RestHandler.cfc
- system/async/tasks/ScheduledTask.cfc
- system/async/time/ChronoUnit.cfc
I believe the intent of this method is to show that a particular handler action is missing which feels more like a 404 not found error.  405 (NOT_ALLOWED) is more appropriate for invalid HTTP actions.
> Updated Missing Action Response Code to 404 instead of 405

- system/async/proxies/Consumer.cfc
- system/async/proxies/Supplier.cfc
- system/async/tasks/ScheduledTask.cfc
- system/testing/VirtualApp.cfc
- system/web/services/InterceptorService.cfc
- tests/specs/web/services/interceptorserviceTest.cfc
This allows simpler removal of closure listeners:
```js
var listener = function() {
// DO STUFF...
};
iService.listen( listener, "onCall" );
// later, when we no longer need the listener:
iService.unlisten( listener, "onCall" );
```
> COLDBOX-1039 - Add unlisten( closure, point ) method to InterceptorService

- system/cache/util/EventURLFacade.cfc
CF-2021 ehCache keys are case sensitive, cache set/get should not be affected by Router.cfc lower or uppercase event-action declaration.
> cf-2021 ehcache keys are case sensitive

- system/Bootstrap.cfc
- system/cache/util/EventURLFacade.cfc
- system/ioc/Injector.cfc
- system/web/services/InterceptorService.cfc
- tests/specs/web/services/interceptorserviceTest.cfc
I propose we add support for passing the point first and closure second. I think it's weird to pass the event name after the function:
```js
variables.interceptorService.listen( function( interceptData ){
// do magic...
}, "ORMPreLoad" );
```
IMHO, this is more legible:
```js
variables.interceptorService.listen( "ORMPreLoad", function( interceptData ){
// do magic...
} );
```
Resolves [COLDBOX-1137](https://ortussolutions.atlassian.net/browse/COLDBOX-1137).
> COLDBOX-1137 - Allow passing closure as second arg to listen() and unlisten() methods

- system/ioc/scopes/CFScopes.cfc
- system/ioc/scopes/CacheBox.cfc
- system/ioc/scopes/RequestScope.cfc
- system/ioc/scopes/Singleton.cfc
- tests/specs/ioc/scopes/CFScopesTest.cfc
- tests/specs/ioc/scopes/CacheBoxTest.cfc
- tests/specs/ioc/scopes/RequestScopeTest.cfc
- tests/specs/ioc/scopes/SingletonTest.cfc
Instead of leaving an incorrectly built instance in a persistent scope, this PR removes any instance from it's scope if it throws during autowiring.
> WIREBOX-132 - Remove throwing instances from scopes

- system/RestHandler.cfc
RestHandler.cfc missing exception information on InvalidCredentials & TokenInvalidException
> error wrappers for rest handlers missing exception

- system/RestHandler.cfc
The Method signature had support for the abort, but it did not actually do anything with it. Add param to javadocs, and used the appropriate code from the onAuthorizationFailure Also updated the comment to say it returns a 401.  Confirmed the http status codes struct has the 401 for NOT_AUTHENTICATED not a 403.
Note: should we implement this abort option on all of the rest handler methods? I think its nice, I assumed it did it automatically since some did do it.
I realize module need the flexibility to abort or not. 
I think cbsecurity might expect that behavior to not abort and continue processing.
> Update RestHandler - Implement abort logic onAuthenticationFailure

- system/testing/BaseTestCase.cfc
This PR improves testing performance by not creating a brand new Controller object each time `getMockRequestContext()` is called if `variables.controller` already exists.
> 🤖 TEST: Reuse existing controller in getMockRequestContext()

- system/web/services/RoutingService.cfc
This functionality needs to be added so that the route visualizer will be able to retrieve all potential route matches in the ColdBox app. 
With this functionality, ColdBox users needing to debug overridden routes will be able to see the list and order in which the routes get matched and can from there fix their router configuration
> Add in functionality to exclude patterns

- system/Bootstrap.cfc
- system/FrameworkSupertype.cfc
- system/web/services/LoaderService.cfc
- tests/suites/loadtests/6load/layouts/Main.cfm
Remove the use of `renderLayout` by `layout` which was logging errors
> Remove use of deprecated methods internally

- .github/workflows/gh-release.yml
- .github/workflows/tests.yml
- system/web/routing/Router.cfc
- tests/specs/testing/BaseInterceptorTest.cfc
Updates for deprecated syntax in older versions of third-party actions:
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> 🐛 FIX: Update GHA dependencies to drop deprecated syntax

- system/async/tasks/ScheduledTask.cfc
- system/web/tasks/ColdBoxScheduler.cfc
**New Properties**
* `annually` 
boolean to flag task as annually scheduled
* `delayTimeUnit`
used to work with delays regardless of setting in chain
* `debug`  
used for debug output
* `firstBusinessDay` 
boolean to flag task as on first business day schedule
* `lastBusinessDay` 
boolean to flag task as on last business day schedule
* `taskTime` 
log of time of day for firstBusinessDay and lastBusinessDay tasks
* `startTime`
limits task to run on or after specific time of day
* `endTime`
limits task to run on or before specific time of day
* `meta`
struct that user can use to store any data for the task ( helpful for building UIs and not having to manage outside of task )
* `stats.nextRun`
missing value from docs now works 😄 
**Fixed**
* `onFirstBusinessDayOfTheMonth()` 
was not properly …
> ColdBox Scheduled Tasks Updates

- system/async/tasks/ScheduledTask.cfc
- system/web/tasks/ColdBoxScheduler.cfc
**New Properties**
* `annually` 
boolean to flag task as annually scheduled
* `delayTimeUnit`
used to work with delays regardless of setting in chain
* `debug`  
used for debug output
* `firstBusinessDay` 
boolean to flag task as on first business day schedule
* `lastBusinessDay` 
boolean to flag task as on last business day schedule
* `taskTime` 
log of time of day for firstBusinessDay and lastBusinessDay tasks
* `startTime`
limits task to run on or after specific time of day
* `endTime`
limits task to run on or before specific time of day
* `meta`
struct that user can use to store any data for the task ( helpful for building UIs and not having to manage outside of task )
* `stats.nextRun`
missing value from docs now works 😄 
**Fixed**
* `onFirstBusinessDayOfTheMonth()` 
was not properly …
> Feature/scheduled tasks updates for 6.8

- .github/workflows/tests.yml
- server-lucee@5.json
- server-lucee@6.json
- server-lucee@be.json
- server-lucee@light.json
Since the latest Lucee builds don't bundle the Hibernate extension, it is time to switch to the Ortus-maintained extension.
> Lucee ORM is no longer being developed or bundled by the Lucee Team, Ortus have forked and taken over the development of ORM for Lucee, see [Introducing: The Ortus ORM Extension](https://www.ortussolutions.com/blog/introducing-the-ortus-orm-extension).
For this reason, we need to install the ortus orm extension into the Lucee builds on server startup, or the builds will fail.
> Install Ortus ORM extension via server.json's env prop

- system/Bootstrap.cfc
Fixed issue with onSessionEnd function when using a COLDBOX_APP_KEY value
If you are using a Coldbox_App_Key value for an application the onSessionEnd function will throw an error since it is hard coded to use the default cbController value instead of using the locateAppKey function.
[[**Please note that all PRs must have tests attached to them**
IMPORTANT: Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.
All PRs must have an accompanied Jira issue. Please make sure you created it and linked it here.
> Bug Tracker: https://ortussolutions.atlassian.net/jira/software/c/projects/COLDBOX/issues](https://ortussolutions.atlassian.net/browse/COLDBOX-1244)](https://ortussolutions.atlassian.net/browse/COLDBOX-1244)
Please delete options that are …
> Bootstrap.cfc onSessionEnd Error

- license.txt
- system/cache/license.txt
- system/ioc/license.txt
- system/logging/license.txt
Consistent American English spelling of "License" -- specifically in the various license.txt files throughout the codebase.
> Consistent American English spelling of "License"

- system/logging/config/LogBoxConfig.cfc
- tests/specs/logging/LogBoxTest.cfc
This PR adds the ability to define LogBox appender exclusions to the root logger and categories by using a special `exclude` key similar to Wirebox's object populator.
Tests included, of course. :)
Addresses: https://ortussolutions.atlassian.net/browse/LOGBOX-70
> Add Ability to Exclude LogBox Appenders to Root Logger and Categories

- system/RestHandler.cfc
currently it handles only InvalidCredentials and TokenInvalidException
Please include a summary of the changes and which issue(s) is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
**Please note that all PRs must have tests attached to them**
IMPORTANT: Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.
All PRs must have an accompanied Jira issue. Please make sure you created it and linked it here.
> Bug Tracker: https://ortussolutions.atlassian.net/jira/software/c/projects/COLDBOX/issues
> RestHandler.cfc should catch NotAuthorized exception

- system/async/tasks/Scheduler.cfc
- system/web/services/SchedulerService.cfc
This PR adds a `restart` method to Schedulers so we can dynamically load tasks in the `configure` method.
`restart` will `shutdown` the Scheduler, clear the tasks, call `configure`, and then `startup` the scheduler.
> Restart the scheduler to call configure again to get new tasks

- system/web/context/RequestContext.cfc
See https://ortussolutions.atlassian.net/browse/COLDBOX-1269 for a discussion on why this PR was created.
Important: Before merging, check line 1816. I'm unclear on the purpose of the `responseHeaders` value in the `variables` scope, but that value will always be overwritten.  If you want to append the header there too, let me know and I will amend the PR.
> Add exception for set-cookie headers to always append

- system/cache/policies/AbstractEvictionPolicy.cfc
- system/cache/store/ConcurrentSoftReferenceStore.cfc
We've recently had ColdBox 7.2.1+13 running under load on ACF 2018 and were frequently getting the following errors of category `coldbox.system.cache.policies.LRU`. We've been running ColdBox 7.2.1+13 for a while on this hardware and it was only when under high load these showed up so probably is rare in the wild.
The changes in this PR are safety checks to ensure the metadata keys exist. We've had these modifications running in production for a week and have no further errors of this type.
COLDBOX-1280 https://ortussolutions.atlassian.net/browse/COLDBOX-1280
- [ x ] Bug Fix
Tests pass, not sure how to write a specific test for it as it seems to only happen under load
Have tried to match existing code style.
> Cache policies LRU error

- system/async/tasks/ScheduledTask.cfc
BoxLang requires the value passed into
java.util.concurrent.TimeUnit to be casted to long to avoid error.
COLDBOX-1282
- [  x ] Bug Fix
> ScheduledTasks Casting Error

- system/core/database/SchemaInfo.cfc
Resolves COLDBOX-1293
https://ortussolutions.atlassian.net/browse/COLDBOX-1293
> COLDBOX-1293 Resolve

- system/ioc/dsl/ColdBoxDSL.cfc
The `thisLocationToken` variable is not var scoped (referenced in case '4')
https://github.com/ColdBox/coldbox-platform/blob/development/system/ioc/dsl/ColdBoxDSL.cfc#L252
Also includes formatting changes to make the initial variable assignments line up.
Please include a summary of the changes and which issue(s) is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
https://ortussolutions.atlassian.net/browse/COLDBOX-1304
> thisLocationToken is not var scoped

- system/web/services/ModuleService.cfc
Pass in the original config settings when appending any custom configs.  This will give developers more flexibility with how they want to override configs and make things easier if the module has a complex config structure.
Currently if you want to override a module's settings, you have to copy/paste the original module config struct, in some modules, this could be HUGE.  What if you just want to override one key within the config struct without overriding the whole thing?
For example:
```
// ModuleConfig.cfc
function configure() {
variables.settings = {
posts: {
enabled: true,
maxLength: 1000,
allowImages: true
},
pages: {
enabled: true,
maxLength: 5000,
allowImages: true
},
users: {
enabled: true,
requireEmailVerification: true,
passwordMin: 8,
passwordMax: 100
}
}
}
```
Let's say in …
> Update Config Seeding to Include Original Module Settings

- system/testing/BaseTestCase.cfc
Here is a POC to fix tests which fail due to headers not being dynamic. 
This should solve the cbotel errors because it expects headers, or default values to work. 
This has been painful for a while, especially in more dynamic testing flows.
I'll let you decide if its worth while or not to make a ticket etc.
> Use a callback to handle dynamic getHttpHeader calls in testing

- system/ioc/dsl/ColdBoxDSL.cfc
- tests/specs/ioc/dsl/ColdBoxDSLTest.cfc
Fixes [COLDBOX-1328](https://ortussolutions.atlassian.net/browse/COLDBOX-1328)
[COLDBOX-1328]: https://ortussolutions.atlassian.net/browse/COLDBOX-1328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Better error messages for ColdBox module setting injections

- system/web/context/RequestContext.cfc
Matches Router.cfc behavior and assume default `statusCode` of 200.
Router handles the default status code by assuming it is 200 unless explicitly set otherwise.  The RequestContext and Router should be consistent in their default assumptions.  Additionally, a `statusCode` of 0 isn't valid in the HTML spec anyway.
https://ortussolutions.atlassian.net/browse/COLDBOX-1338
- [x ] Bug Fix
> Set default request statusCode to 200

- system/cache/util/EventURLFacade.cfc
- system/web/services/HandlerService.cfc
- system/web/services/RequestService.cfc
- test-harness/handlers/eventcaching.cfc
- tests/specs/cache/util/EventsURLFacadeTest.cfc
- tests/specs/integration/EventCachingSpec.cfc
@lmajano 
This pull request is in response to [this discussion](https://community.ortussolutions.com/t/coldbox-6-4-event-caching-and-ignoring-rc-scope/8886) in the Coldbox community and is a revival of the original PR here: https://github.com/ColdBox/coldbox-platform/pull/503
This new feature for Coldbox gives developers more flexibility with event caching and different RC scopes. The end result should be more efficient caching and improved page load speed for many users.
**The Problem:**
Currently, event caching considers the entire RC scope when generating a cache key. This means that changing any URL or FORM variable on a request will force Coldbox to generate a new cache entry. This behavior is problematic for a few reasons:
A malicious attacker could take advantage and create an …
> [COLDBOX-1331] Add ability to ignore or include RC keys when caching events

- system/RestHandler.cfc
[This commit](https://github.com/ColdBox/coldbox-platform/pull/587/files) for COLDBOX-1250: RestHandler.cfc should catch NotAuthorized exception
Resolved
was implemented incorrectly.
Authorization - deals with permissability
Authentication - deals with bad or no credentials
[When cbSecurity throws](https://github.com/coldbox-modules/cbsecurity/blob/6dbcdcac3ae651a3406445ba902733bee5a696b2/models/CBSecurity.cfc#L365) the NotAuthorized exception it is in the context of a permissability check.  As such, the exception is correctly named, but the method it calls is incorrect.
https://ortussolutions.atlassian.net/browse/COLDBOX-1345
> COLDBOX-1345 Resolve
