ColdBox/coldbox-platform

box-logbox.json

changed log box documentation link

fix for logbox-19

---

system/cache/policies/LIFO.cfc

Fixes Cachebox-35

---

system/core/dynamic/BeanPopulator.cfc

GetMetadata in getRelationshipMetaData function replaced by recursive
function collectAllProperties

COLDBOX-485 fix for parent properties (recursive)

---

system/web/Renderer.cfc

* Render Layout and view lookups for conventions even when passing in module arguments
* viewModule fix when passing in viewModule argument to renderLayout + view combo (which didn't work)
* args propagation from layout > view for layout + view rendering combo

Render Layout and view lookups

---

system/web/Renderer.cfc

Reverts ColdBox/coldbox-platform#218

Revert "Render Layout and view lookups"

---

system/aop/Matcher.cfc
system/aop/MethodInvocation.cfc
system/aop/Mixer.cfc
system/aop/MixerUtil.cfc
system/aop/aspects/CFTransaction.cfc
system/aop/aspects/MethodLogger.cfc
tests/specs/ioc/aop/MethodInvocationTest.cfc

Reverts ColdBox/coldbox-platform#238

Revert "COLDBOX CFSCRIPT SYSTEM AOP"

---

system/web/context/RequestContext.cfc

without named arguments, exception will be wrong

fix getValue() to throw exception correctly

---

system/core/dynamic/BeanPopulator.cfc

COLDBOX-487 fix for null Errors in populateFromJson

COLDBOX-487 fix for null Errors in populateFromJson

---

system/core/dynamic/HTMLHelper.cfc

Adds 'property' to HTMLHelper meta-function arguments

Argument: Property

---

system/core/dynamic/HTMLHelper.cfc
system/web/context/RequestContext.cfc

Return the user-desired HTTP method, if given.  Otherwise, return the CGI.REQUEST_METHOD, as usual.
See https://laravel.com/docs/5.2/routing#form-method-spoofing
This will introduce no breaking issues while making it possible for normal forms to follow RESTful routing guidelines.
| HTTP Verb      | Path            | Handler@Action | Used for                                     |
| -------------- | --------------- | -------------- | -------------------------------------------- |
| GET            | `/posts`          | posts@index    | Displays a list of all posts                 |
| GET            | `/posts/new`      | posts@new      | Returns an HTML form for creating a new post |
| POST           | `/posts`          | posts@create   | Creates a new post                           |
| GET …

Return the user-desired HTTP method, if given.

---

system/Bootstrap.cfc
system/cache/providers/CacheBoxProvider.cfc
system/cache/store/ConcurrentSoftReferenceStore.cfc
system/cache/store/ConcurrentStore.cfc
system/core/conversion/XMLConverter.cfc
system/ioc/Builder.cfc
system/ioc/Injector.cfc
system/ioc/scopes/CacheBox.cfc
system/testing/BaseTestCase.cfc

As discussed in https://github.com/ColdBox/coldbox-platform/pull/282

Refactor structKeyExists AND isNull checks to just isNull checks

---

system/core/dynamic/HTMLHelper.cfc

Adds breaks on many-to-one and many-to-many if `showRelations` flag is down
Also cleans up re-declared variables

Adds breaks if showRelations flag is down

---

system/interceptors/SES.cfc

Invalid CFML construct found on line 438 at column 9.

---

system/core/util/Util.cfc
tests/specs/InterceptorTest.cfc
tests/specs/core/util/UtilTest.cfc

See [this comment](https://github.com/ColdBox/coldbox-platform/pull/337#issuecomment-350889290).

Optimizations for grabbing java System in Util

---

system/ioc/Injector.cfc
system/ioc/scopes/CFScopes.cfc
system/ioc/scopes/CacheBox.cfc
system/ioc/scopes/IScope.cfc
system/ioc/scopes/NoScope.cfc
system/ioc/scopes/RequestScope.cfc
system/ioc/scopes/Singleton.cfc

Added exists() to iScope and check if instance exists before
broadcasting 'afterInstanceCreation' event.

COLDBOX-648

---

system/interceptors/SES.cfc

Make it just one `/` instead of two.

Get rid of // at end of SESBaseUrl

---

system/web/services/HandlerService.cfc

https://ortussolutions.atlassian.net/browse/COLDBOX-661

COLDBOX-661 #resolve

---

system/web/routing/Router.cfc

Wrapper to help solve CB4 to CB5 related code like the Route Visualizer
https://github.com/coldbox-modules/route-visualizer/issues/5

getModulesRoutingTable() ColdBox4 Compat wrapper

---

system/web/routing/Router.cfc

Post was incorrectly defaulting to `update` so there was no create option
https://ortussolutions.atlassian.net/browse/COLDBOX-680

Fix Resources for POST=CREATE

---

readme.md

"its not for you" should be "it's not for you". :)

Fixing missing apostrophe.

---

system/FrameworkSupertype.cfc
system/Interceptor.cfc
system/ioc/Builder.cfc
system/web/services/InterceptorService.cfc
system/web/services/ModuleService.cfc
system/web/services/RoutingService.cfc
tests/resources/ChildClass.cfc
tests/resources/VirtualParentClass.cfc
tests/specs/ioc/InjectorCreationTest.cfc
tests/specs/ioc/config/samples/InjectorCreationTestsBinder.cfc

https://ortussolutions.atlassian.net/browse/WIREBOX-77

Fix init call on virtual inheritance

---

system/modules/HTMLHelper/models/HTMLHelper.cfc

Uses a version flag that defaults to 3 to avoid adding a new method.

Add Elixir version 3 path method.

---

system/includes/BugReport.cfm

https://ortussolutions.atlassian.net/browse/COLDBOX-816

lowercase cgi.xxx (returns empty when preservecaseforstructkey) is enabled

---

system/ioc/Builder.cfc

Constructor injection with virtual inheritance doesn't work correctly if the target component does not have a constructor.  The virtual inheritance constructor is injected to the target, but none of the arguments are passed when calling the constructor.  This fixes that problem by adding the constructor arguments of the virtual inheritance mapping to the target mapping.

Fix constructor injection with virtual inheritance

---

system/logging/appenders/DBAppender.cfc

The rotate property is not used, this should toggle log rotation

LOGBOX-38: Use the rotate property

---

system/logging/AbstractAppender.cfc
system/logging/appenders/ConsoleAppender.cfc
system/logging/appenders/FileAppender.cfc

Removed anonymous function and replaced with a UDF as a work around to adobe bug CF-4204874. This is causing a memory leak which ultimately causes my application to crash
See detail bug information here https://tracker.adobe.com/#/view/CF-4204874

Work around for adobe bug CF-4204874

---

system/web/services/ModuleService.cfc

Found a typo in the log message

Fixed typo in ModuleService.cfc

---

system/logging/appenders/ConsoleAppender.cfc

This pull request copies over the new approach making use of the TaskScheduler in the FileAppender to use in the ConsoleAppender as well.

Update ConsoleAppender to use TaskScheduler

---

system/logging/appenders/ConsoleAppender.cfc
tests/specs/logging/appenders/ConsoleAppenderTest.cfc

Left this debug output active, sorry 😳 . I was trying to copy the pattern in the FileAppender of what was left in place of the `out()` calls and what was commented out.

Comment out debug output in ConsoleAppender

---

system/web/routing/Router.cfc
system/web/services/RoutingService.cfc

Resolves [COLDBOX-898](https://ortussolutions.atlassian.net/browse/COLDBOX-898)

Fix for missing port caused by using just CGI.SERVER_NAME

---

system/web/Renderer.cfc

I believe this is the proper way to fix COLDBOX-920?

Correct args for setExplicitView

---

system/RestHandler.cfc

there should be a catch for authorization issues

Update RestHandler.cfc, added catch for onAuthorizationFailure

---

system/cache/providers/CFProvider.cfc
system/core/dynamic/BeanPopulator.cfc

Also resolves CBORM-9 ( https://ortussolutions.atlassian.net/browse/CBORM-9 )

ACF Compatibility update for 2021 version of ORM

---

system/RestHandler.cfc

So it it easier to override default error handling in REST handler

handle any other exceptions in it's own method in REST handler

---

system/async/proxies/BaseProxy.cfc

Resolves an issue where ACF would lose the app scope and usage of the original fusion context would throw a null pointer exception

Fixes issues with Adobe losing App Context in Scheduled Tasks

---

.vscode/settings.json
system/logging/LogBox.cfc
tests/specs/logging/LogBoxTest.cfc

attempt to add the appender to the registry if it exists in the config but not the internal registry

Update internal registry on the fly as possible

---

system/web/context/Response.cfc
tests/specs/cache/providers/CacheBoxProviderTest.cfc
tests/specs/ioc/InjectorCreationTest.cfc
tests/specs/ioc/config/samples/NoScopeBinder.cfc
tests/specs/web/flash/AbstractFlashScopeTest.cfc
tests/specs/web/flash/ColdboxCacheFlashTest.cfc

Handle non uniform pagination keys, while paraming our default.s

Update Response.cfc setPagination

---

system/cache/providers/CacheBoxProvider.cfc

to avoid a lot of log messages

change logging level to debug

---

system/web/context/InterceptorState.cfc

When trying to capture exceptions to a third-party service like
Sentry, any errors from async interceptors are lost.  By announcing
the `onException` event we can still capture these exceptions.

Announce onException interception points for async interceptors

---

apidocs/box.json
system/async/proxies/BaseProxy.cfc
system/testing/BaseTestCase.cfc
tests/specs/async/AsyncManagerSpec.cfc

Use latest DocBox version for speed and fanciness. :wink:

👌 IMPROVE: Upgrade docbox to 3.0

---

readme.md

Fix case of `CFML` in `README`

---

server.json
system/exceptions/Whoops.cfm
system/exceptions/css/syntaxhighlighter-theme.css
system/exceptions/css/whoops.css
system/exceptions/js/sql-brush.js
system/web/context/ExceptionBean.cfc

- sql syntax highlighting
- JSON syntax formatting and highlighting
- corrected indentation and missing empty likes in the file preview
- which also corrected the highlighting of the correct line

Whoops upgrade

---

system/core/conversion/DataMarshaller.cfc
test-harness/handlers/rendering.cfc

COLDBOX-1143

---

system/RestHandler.cfc
system/exceptions/Whoops.cfm

Updated line to use dateTimeFormat with correct mask.
COLDBOX-1154

Updated Whoops.cfm timestamp render

---

system/core/dynamic/BeanPopulator.cfc
system/core/dynamic/ObjectPopulator.cfc
system/core/util/CFMappingHelper.cfc
system/core/util/LuceeMappingHelper.cfc
system/modules/HTMLHelper/models/HTMLHelper.cfc
system/web/context/ExceptionBean.cfc
system/web/routing/Router.cfc
tests/specs/ioc/BuilderTest.cfc
tests/specs/ioc/DelegatorsSpec.cfc
tests/specs/web/routing/RouterTest.cfc

Respect group bindings when declaring resources

---

system/core/dynamic/BeanPopulator.cfc
system/core/dynamic/ObjectPopulator.cfc
system/core/util/CFMappingHelper.cfc
system/core/util/LuceeMappingHelper.cfc
system/modules/HTMLHelper/models/HTMLHelper.cfc
system/web/context/ExceptionBean.cfc
system/web/context/RequestContext.cfc
tests/specs/ioc/BuilderTest.cfc
tests/specs/ioc/DelegatorsSpec.cfc
tests/specs/web/context/RequestContextTest.cfc

Fix getFullURL to not double-encode query strings

---

system/core/dynamic/ObjectPopulator.cfc
system/web/delegates/Population.cfc

🐛 FIX: Show property name in population error message

---

system/FrameworkSupertype.cfc
system/ioc/Builder.cfc
system/ioc/Injector.cfc
system/remote/ColdboxProxy.cfc
system/web/services/RequestService.cfc
tests/specs/logging/LoggerTest.cfc
tests/specs/orm-enabled/HTMLHelperTest.cfc

Fixes a variable typo in the injector

Fix variable typo

---

.github/workflows/tests.yml
server-lucee@6.json
system/FrameworkSupertype.cfc
system/ioc/Builder.cfc
system/ioc/Injector.cfc
system/remote/ColdboxProxy.cfc
system/web/services/RequestService.cfc
tests/specs/logging/LoggerTest.cfc
tests/specs/orm-enabled/HTMLHelperTest.cfc

Allow us to test on Lucee 6 beta releases.
Note that it's not (currently) possible to automatically start the latest beta version of something. The `@be` will prefer the `SNAPSHOT` builds over the `BETA` builds, because the `SNAPSHOTS` are technically more stable.
For now, we'll have to keep manually updating the `server-lucee@6.json` file with the latest Lucee 6 beta version. :shrug:

🤖 TEST: Add Lucee 6 beta testing to builds

---

system/testing/CustomMatchers.cfc

```cfc
expect( event ).toRedirectTo( "Main.index" )
```

Add toRedirectTo custom matcher

---

system/async/time/DateTimeHelper.cfc
tests/specs/async/time/DateTimeHelperSpec.cfc

- Fixed bug in string concatenation
- Added toString() on argument test required by Lucee when a numeric value is sent in
- Updated Test Spec with new test for validateTime and name
COLDBOX-1281
- [ x ] Bug Fix

DateTimeHelper BugFix and Test Update

---

system/web/Renderer.cfc

Resolves COLDBOX-1289
COLDBOX-1289
-

COLDBOX-1289 - Resolve - Ensure Windows OS delimiters are accounted for

---

system/modules/HTMLHelper/models/HTMLHelper.cfc
system/web/routing/Router.cfc

Fix conditionals for Boxlang detection which affect Testbox CFC exection results.  The current checks did not account for CFC execution

Fix frontController checks to account for CFC execution

---

system/remote/ColdboxProxy.cfc

Resolves [COLDBOX-1340](https://ortussolutions.atlassian.net/browse/COLDBOX-1340).
https://ortussolutions.atlassian.net/browse/COLDBOX-1340
[COLDBOX-1340]: https://ortussolutions.atlassian.net/browse/COLDBOX-1340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix ColdboxProxy when context root is empty string

---

system/exceptions/Whoops.cfm

Update Whoops.cfm fix missing space
